// shadcn/ui Button primitive (new-york style).
//
// Generated by the shadcn CLI (`pnpm dlx shadcn@latest add button`) and then
// hand-aligned to Promptibrary's eslint conventions. Only files under
// `src/shared/ui/*` may import this directly — everything else must go through
// the wrapper at `@/shared/ui/button`.

// eslint-disable-next-line no-restricted-imports -- vendored shadcn primitive uses `import * as React` for JSX namespace types; no useEffect call site here
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/shared/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default:
          "bg-accent text-bg-deep shadow hover:bg-accent-warm",
        destructive:
          "bg-status-error text-ink-primary shadow-sm hover:opacity-90",
        outline:
          "border border-border-strong bg-bg-base hover:bg-bg-raised",
        secondary:
          "bg-bg-raised text-ink-primary shadow-sm hover:bg-bg-sunken",
        ghost: "hover:bg-bg-raised",
        link: "text-accent underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

export { Button, buttonVariants };
